CHEMISTS = [
    "Marie Curie",
    "Dmitri Mendeleev",
    "Robert Boyle",
    "Antoine Lavoisier",
    "Linus Pauling",
    "Alfred Nobel",
    "John Dalton",
    "Michael Faraday",
    "Rosalind Franklin",
    "Gilbert N. Lewis",
    "Fritz Haber",
    "Svante Arrhenius",
    "Louis Pasteur",
    "Emil Fischer",
    "Richard Smalley",
    "Ernest O. Lawrence",
    "Ernest Rutherford",
    "Carl Bosch",
    "Jöns Jacob Berzelius",
    "Glenn T. Seaborg",
    "Martin Fruensgard"
]

DEVICES = [
    "Generator",
    "Inverter",
    "Analyzer",
    "Calibrator",
    "Regulator",
    "Detector",
    "Meter",
    "Valve",
    "Distributor",
    "Charger",
    "Oscillator",
    "Modulator",
    "Projector",
    "Controller",
    "Amplifier",
    "Transmitter",
    "Receiver",
    "Converter",
    "Compressor",
    "Relay",
    "Computer"
]

ADJECTIVES = [
    "Sausy",
    "Bitter",
    "Rough",
    "Ambitious",
    "Salty",
    "Smooth",
    "Attractive",
    "Spicy",
    "Crispy",
    "Lazy",
    "Sour",
    "Flat",
    "Busy",
    "Sweet",
    "Modern",
    "Sassy",
    "Royal",
    "Umami",
    "Gourmet",
    "Wet",
    "Nasty"
]
